#!/usr/bin/env bash
#
# print 'Google Chrome.app' pid

usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

# Google Chrome.app/Contents/MacOS/Google Chrome

ps -ax | grep -v grep | grep "Google Chrome.app" | head -1 | awk '{print $1}'
