#!/usr/bin/env bash
#
# print 1 if 'Google Chrome.app' is in fullscreen mode, else 0

usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 0 ]] && usage "$@"

pid="$(chrome-pid)" || exit
[[ -z "$pid" ]] && exit

osascript "${BASH_SOURCE[0]%/*}"/."${BASH_SOURCE[0]##*/}".applescript "$@"

