#!/usr/bin/env bash
#
# enter fullscreen mode

usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 0 ]] && usage "$@"

pid="$(chrome-pid)" || exit
[[ -z "$pid" ]] && exit

fullscreen="$(chrome fullscreen-detect)" || exit
[[ "$fullscreen" == 1 ]] && exit

osascript "${BASH_SOURCE[0]%/*}"/."${BASH_SOURCE[0]##*/}".applescript "$@"
