#!/usr/bin/env bash
#
# kill 'Google Chrome.app' process

usage() {
    echo "usage: $(basename $0)" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

pid="$(chrome-pid)" || exit
[[ -n "$pid" ]] && { kill -9 "$pid" &> /dev/null; exit; };:
